language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: QSRdXSZY1Zgp6iNdyocg9kgV7PgewOdG6DeQT7I10My360qT7PlxsqKEltiGO86dae4AMqErOx/CHzXMOVcMrkE16kqLvPGUhAoKeXBnIyUuEOo8m/ss4Asqreg+nbFPSK+gBeuL5MbUhlGSTccccCAKVfQrtnUTaswFXDsEGCY=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: VZ4ODsb5hO2v1XU4sDDC4EHaH/W4L08bFnT1ZIoKULmypCnSzaaEpbseaupJR8Uyjkj3xlqsnoReuty8ePCZAbD48ZrNMvGZkTmevN7eemuo5Fh/9F7/Z+BQRNf2FrkVQJszu00St3TyqipmoOVojlzSohphStk1541rp3yRlww=
sudo: false
