language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: I5z8wgCCq5HQwN293n/cVu3YlGZIJIJMuK/ceQM9fTXvCmKQ/+4tUsPGC+1tdUGi2yWTzG96EnaU2DhPhW58W/6N1HKJLqkSsIHgh9TpQr8YIdEUGSlfNPzhtS3vunvSZ1SuuO7KoPtlZ+BsJPRAtjs/NmpTu61TXf+oQdMfd5o=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: VZ4ODsb5hO2v1XU4sDDC4EHaH/W4L08bFnT1ZIoKULmypCnSzaaEpbseaupJR8Uyjkj3xlqsnoReuty8ePCZAbD48ZrNMvGZkTmevN7eemuo5Fh/9F7/Z+BQRNf2FrkVQJszu00St3TyqipmoOVojlzSohphStk1541rp3yRlww=
sudo: false
